from typing import Any

class CheapStepper:
    def __init__(self, in1: int, in2: int, in3: int, in4: int):
        ...
    def setRpm(self, rpm: int):
        ...
    def set4076StepMode(self, ):
        ...
    def setTotalSteps(self, numSteps: int):
        ...
    def move(self, clockwise: bool, numSteps: int):
        ...
    def moveTo(self, clockwise: bool, toStep: int):
        ...
    def moveDegrees(self, clockwise: bool, deg: int):
        ...
    def moveToDegree(self, clockwise: bool, deg: int):
        ...
    def moveCW(self, numSteps: int):
        ...
    def moveCCW(self, numSteps: int):
        ...
    def moveToCW(self, toStep: int):
        ...
    def moveToCCW(self, toStep: int):
        ...
    def moveDegreesCW(self, deg: int):
        ...
    def moveDegreesCCW(self, deg: int):
        ...
    def moveToDegreeCW(self, deg: int):
        ...
    def moveToDegreeCCW(self, deg: int):
        ...
    def newMove(self, clockwise: bool, numSteps: int):
        ...
    def newMoveTo(self, clockwise: bool, toStep: int):
        ...
    def newMoveDegrees(self, clockwise: bool, deg: int):
        ...
    def newMoveToDegree(self, clockwise: bool, deg: int):
        ...
    def run(self, ):
        ...
    def stop(self, ):
        ...
    def off(self, ):
        ...
    def newMoveCW(self, numSteps: int):
        ...
    def newMoveCCW(self, numSteps: int):
        ...
    def newMoveToCW(self, toStep: int):
        ...
    def newMoveToCCW(self, toStep: int):
        ...
    def newMoveDegreesCW(self, deg: int):
        ...
    def newMoveDegreesCCW(self, deg: int):
        ...
    def newMoveToDegreeCW(self, deg: int):
        ...
    def newMoveToDegreeCCW(self, deg: int):
        ...
    def step(self, clockwise: bool):
        ...
    def stepCW(self, ):
        ...
    def stepCCW(self, ):
        ...
    def getStep(self, ):
        ...
    def getDelay(self, ):
        ...
    def getRpm(self, ):
        ...
    def getPin(self, p: int):
        ...
    def getStepsLeft(self, ):
        ...
    def calcDelay(self, rpm: int):
        ...
    def calcRpm(self, *args: Any):
        ...
    def seqCW(self, ):
        ...
    def seqCCW(self, ):
        ...
    def seq(self, seqNum: int):
        ...

